#!/usr/bin/env bash
#install nginx and redirects to school string
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
file1=/usr/var/www/html/index.html
sudo bash -c "echo 'Hello World!' > $file1"
service nginx start
