#!/usr/bin/env bash
#install nginx and redirects to school string
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
service nginx start
