#!/usr/bin/env bash
# custom 404 page that contains the string
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
new_location="location /redirect_me {\\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n}"
sudo sed -i "30i $new_location" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
custom_404="error_page 404 /custom_404.html; \\nlocation = /custom_404.html {\\nroot /usr/share/nginx/html; \ninternal;\\n}"
sudo sed -i "34i $custom_404" /etc/nginx/sites-available/default
sudo service nginx restart
