#!/usr/bin/env bash
# a script that uses trap a lot
pgrep -f 100-process_and_pid_file > /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit 1" SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit 1' SIGQUIT
while :;do
    echo To infinity and beyond
    sleep 1
done
